export const BLOG_CATEGORIES = [
  "Technology",
  "Web Development",
  "Design",
  "AI/ML",
  "Career",
  "Startup",
  "Tutorial",
  "News",
  "Tips & Tricks",
  "Case Studies",
] as const;

export type BlogCategory = (typeof BLOG_CATEGORIES)[number];

export interface Blog {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  author: string;
  authorAvatar: string;
  category: BlogCategory;
  tags: string[];
  coverImage: string;
  readTime: number; // in minutes
  likes: number;
  views: number;
  trending: boolean;
  publishedAt: string;
  updatedAt: string;
}

export const blogs: Blog[] = [
  {
    id: "1",
    title: "The Future of Web Development: React vs Vue vs Svelte",
    slug: "future-web-development-frameworks",
    excerpt:
      "A comprehensive comparison of the three major web frameworks and what the future holds for each.",
    content: "Full content here...",
    author: "Sarah Chen",
    authorAvatar: "SC",
    category: "Web Development",
    tags: ["React", "Vue", "Svelte", "JavaScript"],
    coverImage: "/images/blog-1.jpg",
    readTime: 8,
    likes: 2340,
    views: 45200,
    trending: true,
    publishedAt: "2024-03-15",
    updatedAt: "2024-03-20",
  },
  {
    id: "2",
    title: "Getting Started with Machine Learning: A Beginner's Guide",
    slug: "ml-beginners-guide",
    excerpt:
      "Learn the fundamentals of machine learning and start building your first ML model today.",
    content: "Full content here...",
    author: "Dr. James Wilson",
    authorAvatar: "JW",
    category: "AI/ML",
    tags: ["Machine Learning", "Python", "TensorFlow", "Beginner"],
    coverImage: "/images/blog-2.jpg",
    readTime: 12,
    likes: 3210,
    views: 56800,
    trending: true,
    publishedAt: "2024-03-10",
    updatedAt: "2024-03-18",
  },
  {
    id: "3",
    title: "5 UI/UX Design Trends to Watch in 2024",
    slug: "design-trends-2024",
    excerpt:
      "Explore the latest design trends that are reshaping the digital landscape.",
    content: "Full content here...",
    author: "Emma Rodriguez",
    authorAvatar: "ER",
    category: "Design",
    tags: ["UI/UX", "Design Trends", "2024"],
    coverImage: "/images/blog-3.jpg",
    readTime: 6,
    likes: 1890,
    views: 38900,
    trending: false,
    publishedAt: "2024-03-18",
    updatedAt: "2024-03-20",
  },
  {
    id: "4",
    title: "How to Launch Your Startup: A Step-by-Step Guide",
    slug: "startup-launch-guide",
    excerpt:
      "Everything you need to know about starting your own business from idea to launch.",
    content: "Full content here...",
    author: "Michael Brown",
    authorAvatar: "MB",
    category: "Startup",
    tags: ["Startup", "Entrepreneurship", "Business"],
    coverImage: "/images/blog-4.jpg",
    readTime: 15,
    likes: 4120,
    views: 72300,
    trending: true,
    publishedAt: "2024-02-28",
    updatedAt: "2024-03-15",
  },
  {
    id: "5",
    title: "TypeScript Best Practices for Large Projects",
    slug: "typescript-best-practices",
    excerpt:
      "Learn how to structure and maintain large TypeScript projects effectively.",
    content: "Full content here...",
    author: "Alex Kim",
    authorAvatar: "AK",
    category: "Web Development",
    tags: ["TypeScript", "JavaScript", "Best Practices"],
    coverImage: "/images/blog-5.jpg",
    readTime: 10,
    likes: 2560,
    views: 41200,
    trending: true,
    publishedAt: "2024-03-12",
    updatedAt: "2024-03-19",
  },
  {
    id: "6",
    title: "Career Advice: Making the Jump from Junior to Senior Developer",
    slug: "junior-to-senior-developer",
    excerpt:
      "Practical advice on advancing your software development career to the senior level.",
    content: "Full content here...",
    author: "David Lee",
    authorAvatar: "DL",
    category: "Career",
    tags: ["Career", "Software Development", "Growth"],
    coverImage: "/images/blog-6.jpg",
    readTime: 9,
    likes: 3450,
    views: 58900,
    trending: false,
    publishedAt: "2024-03-08",
    updatedAt: "2024-03-17",
  },
  {
    id: "7",
    title: "Building Scalable APIs with Node.js and Express",
    slug: "scalable-apis-nodejs",
    excerpt:
      "Master the techniques for building high-performance, scalable APIs.",
    content: "Full content here...",
    author: "Lisa Zhang",
    authorAvatar: "LZ",
    category: "Tutorial",
    tags: ["Node.js", "API", "Backend"],
    coverImage: "/images/blog-7.jpg",
    readTime: 14,
    likes: 2890,
    views: 49500,
    trending: false,
    publishedAt: "2024-03-05",
    updatedAt: "2024-03-14",
  },
  {
    id: "8",
    title: "Latest News: OpenAI Releases GPT-5 with Revolutionary Features",
    slug: "openai-gpt5-release",
    excerpt:
      "Breaking news about the latest release from OpenAI and its implications.",
    content: "Full content here...",
    author: "Tom Anderson",
    authorAvatar: "TA",
    category: "News",
    tags: ["AI", "OpenAI", "News"],
    coverImage: "/images/blog-8.jpg",
    readTime: 5,
    likes: 5670,
    views: 94200,
    trending: true,
    publishedAt: "2024-03-20",
    updatedAt: "2024-03-20",
  },
  {
    id: "9",
    title: "10 VS Code Extensions That Will Boost Your Productivity",
    slug: "vscode-extensions-productivity",
    excerpt:
      "Discover the essential VS Code extensions every developer should use.",
    content: "Full content here...",
    author: "Nina Patel",
    authorAvatar: "NP",
    category: "Tips & Tricks",
    tags: ["VS Code", "Tools", "Productivity"],
    coverImage: "/images/blog-9.jpg",
    readTime: 7,
    likes: 3120,
    views: 52400,
    trending: false,
    publishedAt: "2024-03-14",
    updatedAt: "2024-03-19",
  },
  {
    id: "10",
    title: "Case Study: How We Scaled Our SaaS to 1M Users",
    slug: "saas-scaling-case-study",
    excerpt:
      "Learn from our experience scaling a SaaS product to over 1 million users.",
    content: "Full content here...",
    author: "Sophia Martinez",
    authorAvatar: "SM",
    category: "Case Studies",
    tags: ["SaaS", "Scaling", "Business"],
    coverImage: "/images/blog-10.jpg",
    readTime: 16,
    likes: 4890,
    views: 78600,
    trending: true,
    publishedAt: "2024-02-25",
    updatedAt: "2024-03-16",
  },
  {
    id: "11",
    title: "Deep Dive: Understanding React Hooks and Custom Hooks",
    slug: "react-hooks-deep-dive",
    excerpt:
      "A comprehensive guide to React hooks and creating custom hooks for reusable logic.",
    content: "Full content here...",
    author: "Kevin Zhang",
    authorAvatar: "KZ",
    category: "Web Development",
    tags: ["React", "Hooks", "JavaScript"],
    coverImage: "/images/blog-11.jpg",
    readTime: 11,
    likes: 3670,
    views: 62100,
    trending: false,
    publishedAt: "2024-03-01",
    updatedAt: "2024-03-13",
  },
  {
    id: "12",
    title: "Ethical AI: Building Responsible Machine Learning Systems",
    slug: "ethical-ai-responsible-ml",
    excerpt:
      "Explore the importance of ethics in AI development and how to build responsible ML systems.",
    content: "Full content here...",
    author: "Dr. Priya Sharma",
    authorAvatar: "PS",
    category: "AI/ML",
    tags: ["AI", "Ethics", "Responsibility"],
    coverImage: "/images/blog-12.jpg",
    readTime: 13,
    likes: 2450,
    views: 44700,
    trending: false,
    publishedAt: "2024-02-20",
    updatedAt: "2024-03-12",
  },
];
