export const CATEGORIES = [
  "Technology",
  "Business",
  "Sports",
  "Music",
  "Health",
  "Gaming",
  "Education",
  "Art",
  "Science",
  "Travel",
] as const;
import { Community, CommunityType, JoinStatus } from "@/types/community";

export const communities: Community[] = [
  {
    id: "1",
    name: "React Developers Hub",
    description: "A place for React developers to learn, share and grow.",
    slug: "react-developers-hub",
    avatar: "/images/community-profile.jpeg",
    coverImage: "/images/community.png",
    category: "Technology",
    type: CommunityType.PUBLIC,
    membersCount: 1243,
    isMember: true,
    joinStatus: JoinStatus.JOINED,
    createdAt: "2026-01-10",
  },
  {
    id: "2",
    name: "Startup Builders",
    description: "Discuss startups, ideas, and business growth strategies.",
    slug: "startup-builders",
    avatar: "/images/community-profile.jpeg",
    coverImage: "/images/community.png",
    category: "Business",
    type: CommunityType.PUBLIC,
    membersCount: 892,
    isMember: false,
    joinStatus: JoinStatus.NONE,
    createdAt: "2026-02-05",
  },
  {
    id: "3",
    name: "Football Fans Arena",
    description: "All about football news, matches, and discussions.",
    slug: "football-fans-arena",
    avatar: "/images/community-profile.jpeg",
    coverImage: "/images/community.png",
    category: "Sports",
    type: CommunityType.PUBLIC,
    membersCount: 2301,
    isMember: false,
    joinStatus: JoinStatus.NONE,
    createdAt: "2025-12-20",
  },
  {
    id: "4",
    name: "Music Producers Circle",
    description: "Share beats, production tips, and collaborate.",
    slug: "music-producers-circle",
    avatar: "/images/community-profile.jpeg",
    coverImage: "/images/community.png",
    category: "Music",
    type: CommunityType.PRIVATE,
    membersCount: 540,
    isMember: false,
    joinStatus: JoinStatus.PENDING,
    createdAt: "2026-01-25",
  },
  {
    id: "5",
    name: "Healthy Living",
    description: "Tips on fitness, nutrition, and mental health.",
    slug: "healthy-living",
    avatar: "/images/community-profile.jpeg",
    coverImage: "/images/community.png",
    category: "Health",
    type: CommunityType.PUBLIC,
    membersCount: 1678,
    isMember: true,
    joinStatus: JoinStatus.JOINED,
    createdAt: "2025-11-15",
  },
  {
    id: "6",
    name: "Gamers Connect",
    description: "Find teammates, discuss games, and share experiences.",
    slug: "gamers-connect",
    avatar: "/images/community-profile.jpeg",
    coverImage: "/images/community.png",
    category: "Gaming",
    type: CommunityType.PUBLIC,
    membersCount: 3100,
    isMember: false,
    joinStatus: JoinStatus.NONE,
    createdAt: "2026-03-01",
  },
  {
    id: "7",
    name: "Study Group Central",
    description: "Collaborate on studies, share resources, and learn together.",
    slug: "study-group-central",
    avatar: "/images/community-profile.jpeg",
    coverImage: "/images/community.png",
    category: "Education",
    type: CommunityType.PRIVATE,
    membersCount: 760,
    isMember: false,
    joinStatus: JoinStatus.NONE,
    createdAt: "2026-02-18",
  },
  {
    id: "8",
    name: "Digital Artists Hub",
    description: "Showcase artwork, get feedback, and improve skills.",
    slug: "digital-artists-hub",
    avatar: "/images/community-profile.jpeg",
    coverImage: "/images/community.png",
    category: "Art",
    type: CommunityType.PUBLIC,
    membersCount: 980,
    isMember: true,
    joinStatus: JoinStatus.JOINED,
    createdAt: "2025-10-30",
  },
  {
    id: "9",
    name: "Science Explorers",
    description: "Discuss scientific discoveries and innovations.",
    slug: "science-explorers",
    avatar: "/images/community-profile.jpeg",
    coverImage: "/images/community.png",
    category: "Science",
    type: CommunityType.PUBLIC,
    membersCount: 1340,
    isMember: false,
    joinStatus: JoinStatus.NONE,
    createdAt: "2026-01-05",
  },
  {
    id: "10",
    name: "Travel Buddies",
    description: "Share travel experiences, tips, and destinations.",
    slug: "travel-buddies",
    avatar: "/images/community-profile.jpeg",
    coverImage: "/images/community.png",
    category: "Travel",
    type: CommunityType.PUBLIC,
    membersCount: 2105,
    isMember: false,
    joinStatus: JoinStatus.NONE,
    createdAt: "2026-03-10",
  },
];

